# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build Services
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build API
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'hueligton/eu-agente'
        command: 'buildAndPush'
        buildContext: '$(Build.Repository.LocalPath)'
        Dockerfile: '**/Api/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
    - task: Docker@2
      displayName: Build Web
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'hueligton/eu-agente-web'
        command: 'buildAndPush'
        buildContext: '$(Build.Repository.LocalPath)'
        Dockerfile: '**/Web/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest