version: '3.4'

services:
  postgres:
    image: postgres:12.2
    container_name: postgresDev
    restart: always
    environment:
      POSTGRES_DB: euagentedb
      POSTGRES_USER: euagente
      POSTGRES_PASSWORD: euagente
      PGDATA: /var/lib/postgresql/data
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:4.11
    container_name: pgadminDev
    environment:
      PGADMIN_DEFAULT_EMAIL: "euagente@email.com"
      PGADMIN_DEFAULT_PASSWORD: "euagente"
    ports:
      - "15433:80"
    volumes:
      - /private/var/lib/pgadmin:/var/lib/pgadmin
      - /tmp/servers.json:/pgadmin4/servers.json
    depends_on:
      - "postgres"

volumes: 
  pgdata: