version: '3.4'

services:
  euagente-api:
    container_name: euagente-api-dev
    image: ${DOCKER_REGISTRY-}api
    build:
      context: Api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - BINGAPIKEY=AqO7YKDLNB1eM3sPSCLRSESMTgcgRews5TpROcyYU9_VGtBDQd0tShArh5Q9lTjE
      - BDCONNECTIONSTRING=Host=postgres;Port=5432;Database=euagentedb;Username=euagente;Password=euagente
      - WEBURL=http://192.168.25.72:32772
      - MailServer=smtp.office365.com
      - MailPort=587
      - MailSenderName="Eu Agente"
      - MailSender=naoresponsa-euagen-te@outlook.com.br
      - MailPassword=033744B4-1C8B-4E69-AC8A-660976D859D3
    ports:
      - "60633:80"

  euagente-web:
    container_name: euagente-web-dev
    image: ${DOCKER_REGISTRY-}web
    build:
      context: Web
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - APIURL=http://192.168.25.72:60633
      - BINGAPIKEY=AqO7YKDLNB1eM3sPSCLRSESMTgcgRews5TpROcyYU9_VGtBDQd0tShArh5Q9lTjE
    ports:
      - "32772:80"